#!/bin/bash

# Script to check which products have recipes and which don't
# Run this to identify why ingredients aren't being deducted

echo "========================================"
echo "RECIPE MAPPING DIAGNOSTIC TOOL"
echo "========================================"
echo ""
echo "This script helps identify why ingredients are not being deducted."
echo ""
echo "STEP 1: Check if your product is in the recipeMapping"
echo "---------------------------------------"
echo ""
echo "Common products that SHOULD have recipes:"
echo "  ✓ Korean Spicy Bulgogi (Pork)"
echo "  ✓ Crispy Pork Lechon Kawali"
echo "  ✓ Chicken Adobo"
echo "  ✓ Fried Chicken"
echo "  ✓ Sizzling Pork Sisig"
echo "  ✓ Pancit Bihon"
echo "  ✓ Spaghetti (Filipino Style)"
echo "  ✓ Special Bulalo"
echo ""
echo "STEP 2: Check if inventory ingredients match recipeMapping"
echo "---------------------------------------"
echo ""
echo "Expected ingredient names in MongoDB (case-insensitive match):"
echo "  - Pork"
echo "  - Chicken"
echo "  - Garlic"
echo "  - Onion"
echo "  - Soy Sauce"
echo "  - Cooking Oil"
echo "  - Salt"
echo "  - Black Pepper"
echo ""
echo "Make sure these match EXACTLY (case-insensitive) with your inventory items!"
echo ""
echo "STEP 3: Verify itemType in MongoDB"
echo "---------------------------------------"
echo ""
echo "Run this MongoDB query to check:"
echo "db.inventoryitems.find({ itemType: 'raw' }, { itemName: 1, itemType: 1 })"
echo ""
echo "All basic ingredients should have itemType = 'raw'"
echo ""
echo "STEP 4: Check server logs when creating a menu item"
echo "---------------------------------------"
echo ""
echo "Look for these patterns:"
echo ""
echo "✅ SUCCESS:"
echo "   🧂 API: Deducting ingredients for: Pork (Qty: 1)"
echo "   ✓ Garlic: 20 → 19 kg"
echo "   ✓ Onion: 30 → 29 kg"
echo ""
echo "❌ FAILURE:"
echo "   ℹ️ No ingredients required for: [Product Name]"
echo "   (This means product is NOT in recipeMapping)"
echo ""
echo "QUICK FIX CHECKLIST"
echo "========================================"
echo "[ ] 1. Product name exists in server.js recipeMapping"
echo "[ ] 2. All ingredient names match inventory itemName values"
echo "[ ] 3. All ingredients have itemType = 'raw' in MongoDB"
echo "[ ] 4. Server is running (check for connection errors)"
echo "[ ] 5. MongoDB is running and accessible"
echo "[ ] 6. Browser console shows API response with deductedIngredients array"
echo ""
echo "To manually test ingredient deduction:"
echo "========================================"
echo ""
echo "1. Open browser DevTools (F12)"
echo "2. Go to Network tab"
echo "3. Create a new menu item"
echo "4. Look for POST request to '/api/inventory/deduct-ingredients'"
echo "5. Check the Response - should show deductedIngredients with changes"
echo ""
echo "If deductedIngredients array is EMPTY, the product has no recipe defined!"
echo ""
